# ============================================================
# Rate Limiter Configuration
# ============================================================
rate-limit.max-requests=5
rate-limit.window-size-in-seconds=10

# Server Configuration
server.port=8080
